# CS 316 : Introduction to Deep Learning
## Lab 01 : Numpy Basics
### Dr. Abdul Samad

# Overview
Hello, students. In this lab, we will go over the fundamentals of Numpy. We'll start with data manipulation and then move on to numpy methods and operators.

# Setup

In [21]:
# Import numpy using the alias np
import numpy as np
np.__version__

'2.1.1'

# 1 - Data Manipulation

A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor corresponds (in math) to a vector. With two axes, a tensor corresponds to a matrix. Tensors with more than two axes do not have special mathematical names.


## Creating Numpy Arrays-Matrices-Tensors

We can use arange to create a row vector x containing the first 12 integers starting with 0, though they are created as floats by default. Each of the values in a tensor is called an element of the tensor. For instance, there are 12 elements in the tensor x. Unless otherwise specified, a new tensor will be stored in main memory and designated for CPU-based computation.

In [22]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

We can access a tensor’s shape (the length along each axis) by inspecting its shape property.

In [23]:
x.shape

(12,)

If we just want to know the total number of elements in a tensor, i.e., the product of all of the shape elements, we can inspect its size. Because we are dealing with a vector here, the single element of its shape is identical to its size.

In [24]:
x.size

12

To change the shape of a tensor without altering either the number of elements or their values, we can invoke the reshape function. For example, we can transform our tensor, x, from a row vector with shape (12,) to a matrix with shape (3, 4). This new tensor contains the exact same values, but views them as a matrix organized as 3 rows and 4 columns. To reiterate, although the shape has changed, the elements have not. Note that the size is unaltered by reshaping. Notice that when we use matrices we also use capital letters.

In [25]:
X = x.reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Furthemore, Numpy also provides the option of transposing a array-matrix-tensor.

In [26]:
np.arange(0,10).reshape(2,5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In some scenarios we may require a array-matrix-tensor of all ones or zero. We can easily create them use the "ones" and "zeros" method.

In [27]:
X = np.zeros((4, 7))
X

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [28]:
X = np.ones((4, 7))
X

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

We can also construct special matrices such as the Diagonal and Identity Matrx.

In [29]:
D = np.diag([2,3,4])
D

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [30]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To create tensor we just add an extra dimension to the shape of numpy object. Lets make a 3x3x3 tensor of all ones.

In [31]:
X = np.ones((3, 3, 3))
X

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

We can also a new axis to an existing array , matrix or tensor. using `np.newaxis`.

In [32]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
b = a[:,:,np.newaxis]
print(b.shape)
print(b)

(3, 3, 1)
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


You can also use the spread operator `...` instead of specifying the indices to add a new axis. 

In [34]:
b = a[...,np.newaxis]
print(b.shape)
print(b)

(3, 3, 1)
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


Often, we want to randomly sample the values for each element in a tensor from some probability distribution. For example, when we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly. The following snippet creates a tensor with shape (3, 4). Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1. We can see that every time we run this cell it creates new random numbers.

In [35]:
np.random.normal(0, 1, size=(3, 4))

array([[-2.52308807, -0.04405547,  0.94477272, -0.08942872],
       [-0.15584532, -0.17596668,  1.93091184, -0.79558212],
       [-1.37032185, -0.32341259,  0.18467872, -0.38555427]])

Numpy also provides options to sample from other distributions such as the uniform distribution.

In [36]:
np.random.rand(5,5)

array([[0.41452291, 0.27075862, 0.92135349, 0.93287415, 0.72165505],
       [0.2621063 , 0.77624017, 0.10047425, 0.97154145, 0.11849235],
       [0.32063292, 0.34295868, 0.59852241, 0.38815798, 0.00714432],
       [0.36731305, 0.95303263, 0.06921334, 0.50906844, 0.88786118],
       [0.96140798, 0.76568776, 0.18934228, 0.1664665 , 0.21798241]])

In [37]:
np.random.uniform(size=(5,5))

array([[0.24085785, 0.14457781, 0.16956868, 0.06157765, 0.33802091],
       [0.13275466, 0.58148226, 0.77937583, 0.88153684, 0.45687925],
       [0.13117779, 0.01630284, 0.6218045 , 0.1897687 , 0.77085668],
       [0.43929058, 0.21643171, 0.03293736, 0.3717314 , 0.70216238],
       [0.16172776, 0.95480156, 0.71044691, 0.31384285, 0.71464142]])

In [38]:
np.random.randint(0,100,(5,5))

array([[96, 14, 57, 61, 68],
       [79, 32, 12, 80, 31],
       [ 3,  0, 54, 37, 51],
       [90, 77, 69, 91, 57],
       [ 1, 58, 27, 85, 58]], dtype=int32)

## Indexing and Slicing

Just as in any other Python array, elements in a tensor can be accessed by index. As in any Python array, the first element has index 0 and ranges are specified to include the first but before the last element. As in standard Python lists, we can access elements according to their relative position to the end of the list by using negative indices.

Thus, [-1] selects the last element and [1:3] selects the second and the third elements as follows:

In [39]:
X = np.arange(12).reshape(3, 4)
X[-1], X[0:2]

(array([ 8,  9, 10, 11]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

Beyond reading, we can also write elements of a matrix by specifying indices.

In [40]:
X[1, 2] = 9
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])

If we want to assign multiple elements the same value, we simply index all of them and then assign them the value. For instance, [0:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column). While we discussed indexing for matrices, this obviously also works for vectors and for tensors of more than 2 dimensions.

In [41]:
X[0:2, :] = 12
X

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]])

In addition to specifying the bounds for accessing the array, we can also specify the stepsize.

In [42]:
r = np.random.rand(5,5)
print(r)


[[0.0661065  0.49358046 0.99739783 0.40160918 0.21853561]
 [0.71293639 0.90898484 0.62439209 0.25362071 0.52760079]
 [0.64594076 0.71009791 0.4908108  0.63665521 0.90057595]
 [0.41907315 0.8952004  0.48591141 0.67178535 0.94708631]
 [0.80741722 0.42735488 0.1555833  0.40167814 0.12925567]]


Here we are accessing all the rows, but only columns 0,2 and because 4 is the maximum bound and 2 is step size.

In [43]:
r[:,0:4:2]

array([[0.0661065 , 0.99739783],
       [0.71293639, 0.62439209],
       [0.64594076, 0.4908108 ],
       [0.41907315, 0.48591141],
       [0.80741722, 0.1555833 ]])

We can also perform the above operation by using `np.arange` instead of providing the indices.

In [44]:
r[:,np.arange(0,4,2)]

array([[0.0661065 , 0.99739783],
       [0.71293639, 0.62439209],
       [0.64594076, 0.4908108 ],
       [0.41907315, 0.48591141],
       [0.80741722, 0.1555833 ]])

Sometimes we want to convert indices between dimension. For example an array containing 100 is reshaped into an array containing 20 rows and 5 columns.

In [45]:
# Convert indices between dimension
a = np.arange(0,100)
np.unravel_index(46,(20,5))

(np.int64(9), np.int64(1))

In [46]:
b = np.arange(0,100).reshape(20,5)
print(b[9,1])

46


Sometimes we are required to access the max or min value in an array. Consequently, we can use the `np.argmax` and `np.argmin`
operators.

In [47]:
# Argmin and Argmax
z = np.random.uniform(0,10,10)
z[z.argmax()]=100
print(z)


[  2.28564737   2.71573098   2.1347704    1.34938562   5.51808149
   2.92181703 100.           1.67358138   3.5854129    5.76517888]


In [48]:
# Argmin and Argmax
z = np.random.uniform(0,10,10)
z[np.argmin(z)]=100
print(z)


[  4.21681308   5.77666386 100.           7.36447341   8.58213724
   7.53680472   7.21648129   7.47105532   5.61543626   9.57597175]


Let's say we want to find the closet value in the array A to the randomnly generated value. We can use the `np.argmin` for this purpose.

In [49]:
z = np.arange(100)
point = np.random.uniform(0,100)
index = np.argmin(np.abs(z-point))
print(f'Point is {point} is close to {z[index]}')

Point is 9.268662260085769 is close to 9


## Questions

We can use the skills that we have learned up until now to create a checkerboard.

In [50]:
# Create a checkerboard
z = np.zeros((8,8))
# Start from the second row, and skip every alternate row.
# Start from the first column, and skip every alternate column.
z[1::2,::2]=1
print(z)

# Start from the first row, and skip every alternate row.
# Start from the second column, and skip every alternate column.
z[::2,1::2]=1
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


We can also add a border of zeros to a matrix of ones.

In [51]:
# Working with borders and adding padding
image = np.ones((10,10))
# For all rows, assign first and last column zero.
image[:,[0,-1]]=0
print(image)
# For the first and last rows,assign all columns zero.
image[[0,-1],:]=0
print(image)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In the previous example, the size of the image remain unchanged. But if we add padding to an image, then we can use the `np.pad` 

In [52]:
image = np.pad(image,pad_width=1)
print(image.shape)

(12, 12)


If we to create a repeating pattern, then we can use the `np.tile`.

In [53]:
np.tile(np.asarray([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 2 - Numpy Operators



In this portion of the lab, we will see at some of the numpy operators. Understanding these will allow you to make your own neural network.

## Vectorized Operations



You may have noticed that numpy arrays have the restriction of just one data type. This homogeneity allows us to apply mathematical operations on each of the element in a numpy array at the same time. Suppose I want to add 2 matrices $A,B$ together, I can either iterate 1 by 1 and compute the result for each value or use numpy and do it together. I can do this operation using `np.add(A,B)` or more succinctly `A+B`. They both generate the same result.

In [54]:
A = np.array([[1,0],[0,1]])
B = np.array([[2,1],[3,2]])
print(np.add(A,B))
#it's better to only use the numpy library
print(A+B)

[[3 1]
 [3 3]]
[[3 1]
 [3 3]]


We can use other operators as well like
1. Subtraction : `np.subtract(A,B)` or `A-B`
2. Multiplication : `np.multiply(A,B)` or `A * B`. **Note that this is element-wise multiplication (Hamdard Product). This is not the same as Matrix Multiplication.**
3. Division: `np.divide(A,B)` or `A/B`.
4. Square: `np.square(A)`
5. Square Root: `np.sqrt(A)`. 
6. Floor: `np.floor(A)`
7. Ceil `np.ceil(A)`

All of these operators are **element-wise** operations.

In [55]:
# Subtraction

Revenue = np.array([1200,2400,3000,4000,5000,5500])
Cost= np.array([1000,2000,2400,3450,4500,4600])

Profit = np.subtract(Revenue,Cost)
print("Subtracting revenue and profit:", Profit)

# Multiplication

Units_Sold = np.array([100,50,300,40,50,550])
Price = np.array([12,48,10,100,100,10])
Rev = np.multiply(Units_Sold,Price)
print("Multiplying the units sold with price:",Rev)


# Division

Prices = np.divide(Rev,Units_Sold)
print("Dividing revenue by units sold to get the price: ",Prices)

# Square

A = np.arange(-3,4)
print("A:",A)
squaredA = np.square(A)
print("A.^2:",squaredA)


# Square root

sqrt_squaredA = np.sqrt(squaredA)
print("Sqrt(A.^2):",sqrt_squaredA)

# Floor A
A = np.random.uniform(0,100,5)
print("A:",A)
floor_A = np.floor(A)
print("Floor A",floor_A)


ceil_A = np.ceil(A)
print("Floor A",ceil_A)

Subtracting revenue and profit: [200 400 600 550 500 900]
Multiplying the units sold with price: [1200 2400 3000 4000 5000 5500]
Dividing revenue by units sold to get the price:  [ 12.  48.  10. 100. 100.  10.]
A: [-3 -2 -1  0  1  2  3]
A.^2: [9 4 1 0 1 4 9]
Sqrt(A.^2): [3. 2. 1. 0. 1. 2. 3.]
A: [49.9817841  34.04062208 98.01194859 83.34064748 28.61864642]
Floor A [49. 34. 98. 83. 28.]
Floor A [50. 35. 99. 84. 29.]


We can also do element wise exponentiation of an array with Numpy. Applying $e^a$ for every element $a$ in $A$

In [56]:
x = np.array([0,1,2,3,4,5,6,7])
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

The `np.vectorize` operators allows to vectorize operations. For example, if we have two Python list, and we add them they will be concated. However, if we have two numpy arrays, then elementwise addition will be performed.

In [57]:
def add(a,b):
    return a+b
a=[1,2,3]
b=[2,3,5]
vecAdd=np.vectorize(add, excluded=["a","b"])
vecAdd1=np.vectorize(add)
print(vecAdd1(a=a,b=b))
print(vecAdd(a=a,b=b))
print(add(a,b))

[3 5 8]
[1, 2, 3, 2, 3, 5]
[1, 2, 3, 2, 3, 5]


## Combining Numpy Operators




Exponentiation is a useful operation which is used in the sigmoid activation function. Sigmoid function is defined as follows:
$$\frac{1}{1+e^{-x}}$$
We can use `np.exp(A)` to take $e^x$ on every element $x$. 
The below example implements this Sigmoid function using exponentiation.
<br>


In [58]:
def sigmoid(x):
	a = np.exp(-x)
	b = np.add(1,a)
	d = np.divide(1,b)
	return d

output_from_layer = np.array([-2,-1,0,1,2])
output_after_sigmoid = sigmoid(output_from_layer)

print(output_after_sigmoid)

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


Batch Normalization is a regularization technique that allows a neural network to learn a more generalised model. In Batch Normalization, you subtract the mean and divide by the standard deviation.

In [59]:
r = np.random.random((5,5))
print(r)
def z_score(mat):
    print(f"Mean : {np.mean(mat)} ; Std : {np.std(mat)}")
    return (mat - np.mean(mat))/np.std(mat)
print(z_score(r))

[[0.29804697 0.56745161 0.45838279 0.07602632 0.2369169 ]
 [0.02362208 0.74302782 0.40278734 0.18797019 0.02561828]
 [0.95691181 0.85054924 0.41209143 0.90241967 0.04978696]
 [0.62463738 0.64788839 0.88115568 0.12728014 0.07153046]
 [0.9241005  0.88357882 0.66133137 0.68141814 0.76472306]]
Mean : 0.498370134305522 ; Std : 0.32118745184198094
[[-0.62369548  0.21508149 -0.12449845 -1.31494493 -0.8140207 ]
 [-1.47810275  0.76172865 -0.29759194 -0.96641367 -1.4718877 ]
 [ 1.42764505  1.09649085 -0.26862413  1.25798669 -1.39663978]
 [ 0.39312635  0.46551711  1.19178237 -1.15536889 -1.32894256]
 [ 1.32548878  1.19932668  0.50737111  0.56991019  0.82927564]]


## np.nan vs np.inf

One thing that should be noted is that `np.nan` is different from `np.inf`. `np.inf` represents positive infinity whereas `np.nan` represents an invalid value. Furthemore, you cannot perform any operations with `np.nan` values. 

We can see that when `np.inf` is compared with 0, the answer is True. However, when `np.nan` is compared with `np.inf`, the answer is False.

In [60]:
# Working with np.nan and np.Inf
print(0*np.inf)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan > np.inf)
print(np.nan < np.nan)
print(np.nan - np.nan)
print(np.inf > 0)

nan
False
False
False
False
nan
True


## Reduction



Sometimes we want to simplify our data. We might be dealing with images and want to convert it into grayscale hence we would need to take the average of the RGB channels. This simplification of data is known as _reduction_. We can perform it on multiple axis, and have functions like sum, average and median. We will motivate this understanding of how we can use axis using an example of pixels. The screen that you have has a width and height. And each pixel has an RGB value.

In [86]:
pixels = np.array([
        [[100,200,220],[110,110,110],[120,100,80]]
         ,[[0,0,0],[255,250,250],[30,50,70]]])
# We have 2 rows, with 3 columns, and each (row,column) pair has 3 values. RGB. The pixel has width 3, and height 2
pixels.shape

(2, 3, 3)

Suppose we want to take the sum of each row, then our axis would be 0 (Row axis)

In [92]:
# pixels1 = pixels
# np.sum(pixels1,axis=0)
# pixels2 = pixels
# np.sum(pixels2,axis=1)
pixels3 = pixels
np.sum(pixels3,axis=2)

array([[520, 330, 300],
       [  0, 755, 150]])

If we want to take median of each column, we can take it on axis 1. (Column axis)

In [88]:
np.median(pixels,axis=1)

array([[110., 110., 110.],
       [ 30.,  50.,  70.]])

Suppose we want to convert the image into grayscale. Then we will take the average of the R,G,B pixels. Hence our axis will be 2.

In [64]:
np.average(pixels,axis=2)

array([[173.33333333, 110.        , 100.        ],
       [  0.        , 251.66666667,  50.        ]])

In [65]:
A=np.arange(10).reshape(2,5)
print(A)
print("Shape of A = ",A.shape)
print(np.max(A,axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of A =  (2, 5)
[4 9]


There exists other functions as well. Like max. You can also apply without specifying the axis. In that case, it will be applied to each element in the matrix.

In [66]:
np.max(pixels)

np.int64(255)

Numpy also provides functions which ignore Nan values when performing operations such as computing the mean or median.

In [67]:
A = np.asarray([0,np.nan,1])
print(np.nanmean(A))
print(np.nanmedian(A))
print(np.nansum(A))

0.5
0.5
1.0


## Non reduction




We can sometimes find it can be useful to keep the number of axes unchanged when invoking the function for calculating the sum or mean. In that case, we can set `keepdims = True` and this will preserve our dimensions.

In [68]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [69]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

For instance, since sum_A still keeps its two axes after summing each row, we can divide `A` by `sum_A` with broadcasting.

In [70]:
A / sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

If we want to calculate the cumulative sum of elements of A along some axis, say axis=0 (row by row), we can call the `cumsum` function. This function will not reduce the input tensor along any
axis.

In [71]:
A.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]])

## Dot Product



So far, we have only performed elementwise operations, sums, and averages. We can now move on to the domain of Linear Algebra. One of the most fundamental operations is the dot product. Given two vectors $x, y \in  \mathbb{R}^d$, their _dot product_ $\mathbf{x}^⊤\mathbf{y}$ (or $\langle x, y\rangle$) is a sum over the products of the elements at the same position
$$\mathbf{x}^⊤\mathbf{y} = \sum_{i=1}^{d} x_i y_i$$

In [72]:
x = np.arange(4)
y = np.ones(4)
# We use the np.dot function for dot products
x,y, np.dot(x,y)

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), np.float64(6.0))

Dot products are useful in a wide range ofcontexts. For example, given some set of values, denoted by a vector $x \in \mathbb{R}^d$ and a set of weights denoted by $w \in \mathbb{R}^d$, the weighted sum of the values in $x$ according to the weights $w$ could be expressed as the dot product $\mathbf{x}^⊤\mathbf{w}$. When the weights are
non-negative and sum to one (i.e., ($\sum_{i=1}^{d} w_i = 1$), the dot product expresses a _weighted average._
)

## Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A way to overcome this is to duplicate the smaller array so that it is the dimensionality and size as the larger array. This is called array broadcasting and is available in NumPy when performing array arithmetic, which can greatly reduce and simplify your code.

In [73]:
# adding a sclar to array  
A = np.array([1,2,3])
b= 3.0
print(A+b)

[4. 5. 6.]


In [74]:
# adding a sclar to matrix
A = np.array([[1,2,3],[1,2,3]])
print(A)
b= 3.0
print(A+b)

[[1 2 3]
 [1 2 3]]
[[4. 5. 6.]
 [4. 5. 6.]]


In [75]:
A = np.array([[1,2,3],[1,2,3]])
print(A)
B=np.array([1,1,3]).reshape(1,3)
print(A+B)


[[1 2 3]
 [1 2 3]]
[[2 3 6]
 [2 3 6]]


## Filtering

Sometimes we may need to extract the non-zero values from an array. Consequently, we can use the `np.nonzero()` method to get index of the non-zero values.

In [76]:
# Get non-zero values
a = [0,1,0,0,2,5]
index = np.nonzero(a)
np.asarray(a)[index]

array([1, 2, 5])

We can also specify multiply conditions and then combine to extract values from an array.

In [77]:
# Conditioning on an array
a = np.arange(10)
condition1 = a<=6
condition2 = a>=3
a[np.logical_and(condition1,condition2)] = 0  

Sometimes we need to filter an array and then perform an operator. For example, assigning the Class 0 when the logit score is less than 0.5 and assigning the Class 1 otherwise.

In [78]:
r = np.random.rand(10)
print(r)


[0.44525378 0.27849339 0.14044381 0.07361208 0.85616845 0.08867483
 0.9928736  0.67742875 0.76697097 0.5839283 ]


In [79]:
new_class = np.where(r >= 0.5, 1, 0)
print(new_class)

[0 0 0 0 1 0 1 1 1 1]


## Datetime

Numpy allows you to work with dates

In [80]:
# Working with datetime
np.datetime64('today')

np.datetime64('2024-09-11')

In [81]:
np.datetime64('today')-np.timedelta64(1)

np.datetime64('2024-09-10')

In [82]:
np.arange('2022-01','2022-07',dtype='datetime64[{D}]'.format(D='M'))

array(['2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06'],
      dtype='datetime64[M]')

In [83]:
np.arange('2022-01','2024-07',dtype='datetime64[{D}]'.format(D='Y'))

array(['2022', '2023'], dtype='datetime64[Y]')

In [84]:
np.arange('2022-06','2022-07',dtype='datetime64[{D}]'.format(D='D'))

array(['2022-06-01', '2022-06-02', '2022-06-03', '2022-06-04',
       '2022-06-05', '2022-06-06', '2022-06-07', '2022-06-08',
       '2022-06-09', '2022-06-10', '2022-06-11', '2022-06-12',
       '2022-06-13', '2022-06-14', '2022-06-15', '2022-06-16',
       '2022-06-17', '2022-06-18', '2022-06-19', '2022-06-20',
       '2022-06-21', '2022-06-22', '2022-06-23', '2022-06-24',
       '2022-06-25', '2022-06-26', '2022-06-27', '2022-06-28',
       '2022-06-29', '2022-06-30'], dtype='datetime64[D]')